In [1]:
#WAP in python to implement the following Image filtering technique
A)Low pass filtering
B)High pass filtering
c)Median  filtering
d)Mean filtering

SyntaxError: unmatched ')' (2156058838.py, line 2)

In [5]:
#low pass spatial domain filtering
#to observe the blurring effect
import cv2
import numpy as np
img=cv2.imread('ns.png',0)
print(img.ndim)
print(img)


2
[[246   0 249 ... 248 248 248]
 [247 249 250 ... 245 245 245]
 [  0 250 251 ... 243 243 255]
 ...
 [233 233 232 ... 156 150 165]
 [255 233 232 ... 157 149 165]
 [233 233 232 ... 161 150 162]]


In [8]:
m,n =img.shape
print(m)
print(n)

440
455


In [9]:
#Develop Averaging filter(3,3) mask
mask=np.ones([3,3],dtype=int)
mask= mask / 9
print(mask)
print(mask.ndim)

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
2


In [11]:
img_new = np.zeros([m, n])
for i in range(1, m-1):
    for j in range(1, n-1):
        temp = img[i-1, j-1]*mask[0, 0]+img[i-1, j]*mask[0, 1]+img[i-1, j + 1]*mask[0, 2]+img[i, j-1]*mask[1, 0]+ img[i, j]*mask[1, 1]+img[i, j + 1]*mask[1, 2]+img[i + 1, j-1]*mask[2, 0]+img[i + 1, j]*mask[2, 1]+img[i + 1, j + 1]*mask[2, 2]
        img_new[i, j]= temp
print(img_new) 

[[  0.           0.           0.         ...   0.           0.
    0.        ]
 [  0.         193.55555556 222.         ... 246.11111111 246.66666667
    0.        ]
 [  0.         193.66666667 221.55555556 ... 245.77777778 245.55555556
    0.        ]
 ...
 [  0.         235.11111111 232.         ... 158.22222222 158.11111111
    0.        ]
 [  0.         235.11111111 232.         ... 158.44444444 157.22222222
    0.        ]
 [  0.           0.           0.         ...   0.           0.
    0.        ]]


In [6]:
print(img_new)

[[  0.           0.           0.         ...   0.           0.
    0.        ]
 [  0.         193.55555556 222.         ... 246.11111111 246.66666667
    0.        ]
 [  0.         193.66666667 221.55555556 ... 245.77777778 245.55555556
    0.        ]
 ...
 [  0.         235.11111111 232.         ... 158.22222222 158.11111111
    0.        ]
 [  0.         235.11111111 232.         ... 158.44444444 157.22222222
    0.        ]
 [  0.           0.           0.         ...   0.           0.
    0.        ]]


In [14]:
img_new= img_new.astype(np.uint8)
cv2.imwrite( 'LP.png',img_new)
cv2.imshow("Low pass filtered img",img_new)
cv2.waitKey(0)

32

In [ ]:
#High Pass Filtering

In [ ]:
mask=np.array([[-1/9,-1/9,-1/9],[-1/9,8/9,-1/9],[-1/9,-1/9,-1/9]])