In [1]:
import cv2
import numpy as np
img=cv2.imread('ns.png',0)
print(img.ndim)
print(img)

2
[[246   0 249 ... 248 248 248]
 [247 249 250 ... 245 245 245]
 [  0 250 251 ... 243 243 255]
 ...
 [233 233 232 ... 156 150 165]
 [255 233 232 ... 157 149 165]
 [233 233 232 ... 161 150 162]]


In [2]:
m,n =img.shape

In [3]:
mask=np.array([[-1/9,-1/9,-1/9],[-1/9,8/9,-1/9],[-1/9,-1/9,-1/9]])
print(mask)
print(mask.ndim)

[[-0.11111111 -0.11111111 -0.11111111]
 [-0.11111111  0.88888889 -0.11111111]
 [-0.11111111 -0.11111111 -0.11111111]]
2


In [7]:
img_new = np.ones([m, n])
 

for i in range(1, m-1):
    for j in range(1, n-1):
        temp = img[i-1, j-1]*mask[0, 0]+img[i-1, j]*mask[0, 1]+img[i-1, j + 1]*mask[0, 2]+img[i, j-1]*mask[1, 0]+ img[i, j]*mask[1, 1]+img[i, j + 1]*mask[1, 2]+img[i + 1, j-1]*mask[2, 0]+img[i + 1, j]*mask[2, 1]+img[i + 1, j + 1]*mask[2, 2]
        img_new[i, j]= temp

In [5]:
print(img_new)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.54444444e+01  2.80000000e+01 ... -1.11111111e+00
  -1.66666667e+00  0.00000000e+00]
 [ 0.00000000e+00  5.63333333e+01  2.94444444e+01 ... -2.77777778e+00
  -2.55555556e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00 -2.11111111e+00  1.77635684e-14 ... -2.22222222e+00
  -8.11111111e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.11111111e+00  1.77635684e-14 ... -1.44444444e+00
  -8.22222222e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]


In [8]:
img_new= img_new.astype(np.uint8)
cv2.imwrite( 'HP.png',img_new)

True