In [5]:
import cv2
import numpy as np
img_noisy1=cv2.imread('ns.png',0)
print(img_noisy1.ndim)
print(img_noisy1)

2
[[246   0 249 ... 248 248 248]
 [247 249 250 ... 245 245 245]
 [  0 250 251 ... 243 243 255]
 ...
 [233 233 232 ... 156 150 165]
 [255 233 232 ... 157 149 165]
 [233 233 232 ... 161 150 162]]


In [6]:
m,n =img_noisy1.shape

In [7]:
# Traverse the image. For every 3X3 area,
# find the median of the pixels and
# replace the center pixel by the median
img_new1 = np.zeros([m, n])

for i in range(1, m-1):
    for j in range(1, n-1):
        temp = [img_noisy1[i-1, j-1],
            img_noisy1[i-1, j],
            img_noisy1[i-1, j + 1],
            img_noisy1[i, j-1],
            img_noisy1[i, j],
            img_noisy1[i, j + 1],
            img_noisy1[i + 1, j-1],
            img_noisy1[i + 1, j],
            img_noisy1[i + 1, j + 1]]

        temp = sorted(temp)
        img_new1[i, j]= temp[4]

img_new1 = img_new1.astype(np.uint8)
cv2.imwrite('new_median_filtered.png', img_new1)


True

In [9]:

cv2.imshow("Median filtered img",img_new1)
cv2.waitKey(0)
img_new1= img_new1.astype(np.uint8)
cv2.imwrite( 'MF.png',img_new1)
cv2.imshow("Median filtered img",img_new1)
cv2.waitKey(0)

-1