In [2]:
#Installing prerequisite libraries
!pip install pillow
!pip install pandas
!pip install numpy

In [3]:
#A)Open the Image
from PIL import Image
img=Image.open('elon.jpg')

In [4]:
#B)Show the Image
display(img)

In [5]:
#C)Display the basic Image properties
print('Format / Type of the image:' ,img.format)
print(img.mode)
print(img.size)
print(img.width)
print(img.height)

Format / Type of the image: JPEG
RGB
(564, 807)
564
807


In [6]:
#D)Using pillow load an Image & Convert it into an array.
#Also display the properties of image array
from PIL import Image
from numpy import asarray
import numpy
#load the image
img = Image.open("elon.jpg")
#Convert image to numpy array
data = asarray(img)
print(data)
print(len(data))
print(data.shape)

[[[115 118 127]
  [115 118 127]
  [115 118 127]
  ...
  [ 81  79  84]
  [ 80  78  83]
  [ 80  78  83]]

 [[115 118 127]
  [115 118 127]
  [115 118 127]
  ...
  [ 80  78  83]
  [ 79  77  82]
  [ 79  77  82]]

 [[115 118 127]
  [115 118 127]
  [115 118 127]
  ...
  [ 79  77  82]
  [ 78  76  81]
  [ 77  75  80]]

 ...

 [[ 24  15  16]
  [ 24  15  16]
  [ 24  15  16]
  ...
  [ 13   9  10]
  [ 13   9  10]
  [ 13   9  10]]

 [[ 24  15  16]
  [ 24  15  16]
  [ 24  15  16]
  ...
  [ 14  10  11]
  [ 14  10  11]
  [ 14  10  11]]

 [[ 24  15  16]
  [ 24  15  16]
  [ 24  15  16]
  ...
  [ 13   9  10]
  [ 13   9  10]
  [ 13   9  10]]]
807
(807, 564, 3)


In [7]:
#E)Using pillow load the Image & convert it into numpy array 
#Report shape of the array
#Finally Convert the array back into Pillow Image
#Print Details(format,mode,size,width,height)
from PIL import Image
from numpy import asarray
import numpy
#load the image
img = Image.open('elon.jpg')
data=asarray(img)
print(data)
print(data.shape)
print(data.size)
data2=Image.fromarray(data)
print(data2)

[[[115 118 127]
  [115 118 127]
  [115 118 127]
  ...
  [ 81  79  84]
  [ 80  78  83]
  [ 80  78  83]]

 [[115 118 127]
  [115 118 127]
  [115 118 127]
  ...
  [ 80  78  83]
  [ 79  77  82]
  [ 79  77  82]]

 [[115 118 127]
  [115 118 127]
  [115 118 127]
  ...
  [ 79  77  82]
  [ 78  76  81]
  [ 77  75  80]]

 ...

 [[ 24  15  16]
  [ 24  15  16]
  [ 24  15  16]
  ...
  [ 13   9  10]
  [ 13   9  10]
  [ 13   9  10]]

 [[ 24  15  16]
  [ 24  15  16]
  [ 24  15  16]
  ...
  [ 14  10  11]
  [ 14  10  11]
  [ 14  10  11]]

 [[ 24  15  16]
  [ 24  15  16]
  [ 24  15  16]
  ...
  [ 13   9  10]
  [ 13   9  10]
  [ 13   9  10]]]
(807, 564, 3)
1365444
<PIL.Image.Image image mode=RGB size=564x807 at 0x22AC6BD6A60>
